apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mydeploy
  labels:
    app:  mydeploy
spec:
  selector:
    matchLabels:
      app: mydeploy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mydeploy
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mydeploy
        image:  saimonand/img-devops:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: myconf
              key: PORT
        ports:
        - containerPort:  5000
          name:  myconf
