# Use a imagem oficial do Python
FROM python:3.8-slim

# Cria e define o diretório de trabalho
WORKDIR /app

# Copia os requisitos para o contêiner
COPY requirements.txt .

# Instala as dependências
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copia o código fonte para o contêiner
COPY . .

# Expor a porta em que o aplicativo vai rodar
EXPOSE 5000

# Comando para iniciar o aplicativo quando o contêiner iniciar
CMD ["python", "app.py"]
