apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myservice
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: myservice
    protocol: TCP
    port: 5000
    targetPort: 5000